### ISSUE TITLE
Please use standard GH based tests

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.opcua#32]
This adapter does not (yet) use standard GitHub based tests. Please replace test-and-release workflow by standard workflow (see https://github.com/ioBroker/ioBroker.example)

Of course its ok to implement additional tests. Please consider placing them into a seperated workflow to ease checks during stable review.

Standard GitHub tests must be executed and succeed for all supported node versions on all supported platforms.
Currently the named tests only empty shells incorrectly indicating that a test is executed. But

- package test ist missing
- lint is missing (not required but recommended)
- integration test is missing

So please replace test-and-release workflow by standard workflow. I can provide a PR, please ask if  desider.

**Comment by Apollon77** [comment]
Ok, it seems that there are some legacy tests from mqtt adapter copied in test dir which are not executed ... so yes adding standard testing should be easy

**Comment by mcm1957** [comment]
Tst will be added by PR https://github.com/ioBroker/ioBroker.opcua/pull/42

**Comment by mcm1957** [comment]
@Apollon77 
see pending PR
