### ISSUE TITLE
"File index.html not found"

### ISSUE THREAD

**Issue by jnsw** [ioBroker/ioBroker.opcua#5]
If I want to configure the instance, I get "File index.html not found". Is this normal? Running admin@4.0.10

**Comment by Apollon77** [comment]
How you installed the adapter? This adapter is not installable via Github, usere repository only

**Comment by jnsw** [comment]
I used "Adapter aus beliebiger Quelle installieren oder aktualisieren" und put the URL of this repo in it

**Comment by Apollon77** [comment]
Exactly this is not possible for this adapter and also NOT the common way! Only use this if an developer told you so or you want to test a new version from a Forum test thread. Else ALWAYS use the stable (or of you want latest but pot. not stable versions) the latest repository

**Comment by jnsw** [comment]
Thanks! I installed it directly with https://www.npmjs.com/package/iobroker.opcua
